apiVersion: 1

datasources:
  - name: IBEE_DB
    type: postgres
    uid: ibee_postgres
    url: db:5432
    user: ibee
    secureJsonData:
      password: ibee
    jsonData:
      database: ibee
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: true       # tells Grafana to use TimescaleDB optimisations
    isDefault: true
    editable: true