[general]
# v4 expects an integer log level (default 4 = info)
log_level=4

[integration]
marshaler="protobuf"

[integration.mqtt]
event_topic_template="gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="gateway/{{ .GatewayID }}/command/#"

[integration.mqtt.auth]
type="generic"

[integration.mqtt.auth.generic]
servers=[
  "tcp://mqtt:1883",
]

[backend]
type="semtech_udp"

[backend.semtech_udp]
udp_bind="0.0.0.0:1700"
